### ISSUE TITLE
Grafana dashboard does not reappear in grafana after shutdown

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/grafana-k8s-operator#221]
### Bug Description

[Read this post on discourse](https://discourse.charmhub.io/t/grafana-dashboard-does-not-reappear-in-grafana-after-shutdown/10850).

> Hi, We are continuously tinkering with the COS-stack and grafana-agent. One thing I noticed is that dashboards sent from grafana-agent doesn’t reappear in grafana after the computer has been of for a couple of days. Even though the relation is still maintained.
>
> After booting the machine 

![1](https://github.com/canonical/grafana-k8s-operator/assets/939888/55f2914b-286d-4cfc-ba22-840dc82c1d4d)

![2](https://github.com/canonical/grafana-k8s-operator/assets/939888/1ab16a65-47c0-4023-8c8a-c8fb5870b911)

After redoing the relation 

![3](https://github.com/canonical/grafana-k8s-operator/assets/939888/d9a5a228-f9f1-4856-a5c0-a5408be67c6c)

![4](https://github.com/canonical/grafana-k8s-operator/assets/939888/7b8b5a15-a39b-4a1f-8530-56d62f6c2ba3)

Alert rules does appear. Any idea why?

### To Reproduce

-

### Environment

juju 2.9.42

### Relevant log output

```shell
-
```

**Comment by sed-i** [comment]
A similar issue was discovered by @amandahla.
To reproduce:
1. Pack commit b812866392f15c40c5fb809f496f4e3cc5b7b603 from https://github.com/canonical/synapse-operator/pull/17
2. Set update status hook interval to 5m:  `juju model-config update-status-hook-interval=5m`
3. Deploy the following bundle.
4. The dashboard isn't there: `juju ssh --container grafana gr2/0 ls /etc/grafana/provisioning/dashboards` even though it is present in relation data (`juju show-unit gr2/0`

```yaml
bundle: kubernetes
applications:
  gr2:
    charm: grafana-k8s
    channel: edge
    revision: 87
    series: focal
    resources:
      grafana-image: 56
      litestream-image: 37
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  loki-k8s:
    charm: loki-k8s
    channel: edge
    revision: 96
    series: focal
    resources:
      loki-image: 80
    scale: 1
    constraints: arch=amd64
    storage:
      active-index-directory: kubernetes,1,1024M
      loki-chunks: kubernetes,1,1024M
  pr2:
    charm: prometheus-k8s
    channel: edge
    revision: 135
    series: focal
    resources:
      prometheus-image: 114
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  synapse:
    charm: ./synapse-operator/synapse_ubuntu-22.04-amd64.charm
    series: jammy
    resources:
      synapse-image: ghcr.io/canonical/synapse:e9c2a9adc72c40d31e5fc3a1651ed834a91170482c588679471ba42680d98bea
    scale: 1
    options:
      server_name: banana
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
relations:
- - pr2:grafana-source
  - gr2:grafana-source
- - synapse:metrics-endpoint
  - pr2:metrics-endpoint
- - gr2:grafana-dashboard
  - synapse:grafana-dashboard
```
