### ISSUE TITLE
State changing too quickly

### ISSUE THREAD

**Issue by natalytvinova** [canonical/grafana-k8s-operator#339]
### Bug Description

Hi team, 
After a fresh deployment I can not integrate the charm with anything because of this error:
```
$ juju consume mk8s-controller:admin/cos.grafana cos-grafana
ERROR could not consume admin/cos.grafana: cannot add saas application "cos-grafana": state changing too quickly; try again soon
```
This happens every redeployment. At the same time in juju the model looks active/idle. This happens with both openstack and microk8s models integrations. 

### To Reproduce

```
bundle: kubernetes
saas:
  remote-dbff704cb626428485cfa86166164c03: {}
  remote-df1875fc4dd84eba81b59aeb02cdd776: {}
applications:
  alertmanager:
    charm: alertmanager-k8s
    channel: latest/stable
    revision: 113
    base: ubuntu@20.04/stable
    resources:
      alertmanager-image: 91
    scale: 1
    storage:
      data: kubernetes,1,20480M
    trust: true
  ca:
    charm: self-signed-certificates
    channel: latest/edge
    revision: 147
    scale: 1
    options:
      ca-common-name: traefik-0.traefik-endpoints.cos.svc.cluster.local
  catalogue:
    charm: catalogue-k8s
    channel: latest/stable
    revision: 38
    base: ubuntu@20.04/stable
    resources:
      catalogue-image: 32
    scale: 1
    options:
      description: "Canonical Observability Stack Lite, or COS Lite, is a light-weight,
        highly-integrated, \nJuju-based observability suite running on Kubernetes.\n"
      tagline: Model-driven Observability Stack deployed with a single command.
      title: Canonical Observability Stack
    trust: true
  external-ca:
    charm: self-signed-certificates
    channel: latest/edge
    revision: 147
    scale: 1
    options:
      ca-common-name: traefik-0.traefik-endpoints.cos.svc.cluster.local
  grafana:
    charm: grafana-k8s
    channel: latest/stable
    revision: 113
    base: ubuntu@20.04/stable
    resources:
      grafana-image: 68
      litestream-image: 43
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,20480M
    trust: true
  loki:
    charm: loki-k8s
    channel: latest/edge
    revision: 158
    base: ubuntu@20.04/stable
    resources:
      node-exporter-image: 2
    scale: 1
    constraints: arch=amd64
    storage:
      active-index-directory: kubernetes,1,2048M
      loki-chunks: kubernetes,1,184320M
    trust: true
  prometheus:
    charm: prometheus-k8s
    channel: latest/stable
    revision: 189
    base: ubuntu@20.04/stable
    resources:
      prometheus-image: 144
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,184320M
    trust: true
  scrape-interval-config-metrics:
    charm: prometheus-scrape-config-k8s
    channel: latest/stable
    revision: 48
    base: ubuntu@20.04/stable
    scale: 1
    options:
      scrape_interval: 5m
      scrape_timeout: 30s
    trust: true
  scrape-interval-config-monitors:
    charm: prometheus-scrape-config-k8s
    channel: latest/stable
    revision: 48
    base: ubuntu@20.04/stable
    scale: 1
    options:
      scrape_interval: 5m
      scrape_timeout: 30s
    trust: true
  traefik:
    charm: traefik-k8s
    channel: latest/stable
    revision: 191
    base: ubuntu@20.04/stable
    resources:
      traefik-image: 159
    scale: 1
    options:
      external_hostname: observability.<redacted>
    storage:
      configurations: kubernetes,1,1024M
    trust: true
relations:
- - traefik:ingress
  - alertmanager:ingress
- - catalogue:ingress
  - traefik:ingress
- - catalogue:catalogue
  - alertmanager:catalogue
- - external-ca:certificates
  - traefik:certificates
- - ca:send-ca-cert
  - traefik:receive-ca-cert
- - ca:certificates
  - alertmanager:certificates
- - ca:certificates
  - catalogue:certificates
- - scrape-interval-config-monitors:configurable-scrape-jobs
  - remote-df1875fc4dd84eba81b59aeb02cdd776:downstream-prometheus-scrape
- - traefik:ingress-per-unit
  - prometheus:ingress
- - traefik:ingress-per-unit
  - loki:ingress
- - traefik:traefik-route
  - grafana:ingress
- - prometheus:alertmanager
  - alertmanager:alerting
- - grafana:grafana-source
  - prometheus:grafana-source
- - grafana:grafana-source
  - loki:grafana-source
- - grafana:grafana-source
  - alertmanager:grafana-source
- - loki:alertmanager
  - alertmanager:alerting
- - prometheus:metrics-endpoint
  - traefik:metrics-endpoint
- - prometheus:metrics-endpoint
  - alertmanager:self-metrics-endpoint
- - prometheus:metrics-endpoint
  - loki:metrics-endpoint
- - prometheus:metrics-endpoint
  - grafana:metrics-endpoint
- - grafana:grafana-dashboard
  - loki:grafana-dashboard
- - grafana:grafana-dashboard
  - prometheus:grafana-dashboard
- - grafana:grafana-dashboard
  - alertmanager:grafana-dashboard
- - catalogue:catalogue
  - grafana:catalogue
- - catalogue:catalogue
  - prometheus:catalogue
- - scrape-interval-config-metrics:metrics-endpoint
  - prometheus:metrics-endpoint
- - scrape-interval-config-monitors:metrics-endpoint
  - prometheus:metrics-endpoint
- - ca:certificates
  - prometheus:certificates
- - ca:certificates
  - grafana:certificates
- - ca:certificates
  - loki:certificates
--- # overlay.yaml
applications:
  alertmanager:
    offers:
      alertmanager:
        endpoints:
        - karma-dashboard
        acl:
          admin: admin
  grafana:
    offers:
      grafana:
        endpoints:
        - grafana-dashboard
        acl:
          admin: admin
  loki:
    offers:
      loki:
        endpoints:
        - logging
        acl:
          admin: admin
  prometheus:
    offers:
      prometheus:
        endpoints:
        - metrics-endpoint
        - receive-remote-write
        acl:
          admin: admin
  scrape-interval-config-metrics:
    offers:
      scrape-interval-config-metrics:
        endpoints:
        - configurable-scrape-jobs
        acl:
          admin: admin
  scrape-interval-config-monitors:
    offers:
      scrape-interval-config-monitors:
        endpoints:
        - configurable-scrape-jobs
        acl:
          admin: admin
```

```
$ juju status --relations
Model  Controller            Cloud/Region                      Version  SLA          Timestamp
cos    sncf-mk8s-controller  snapped-microk8s_cloud/localhost  3.5.1    unsupported  06:46:41Z

App                              Version  Status  Scale  Charm                         Channel        Rev  Address         Exposed  Message
alertmanager                     0.27.0   active      1  alertmanager-k8s              latest/stable  113  10.152.183.92   no       
ca                                        active      1  self-signed-certificates      latest/edge    147  10.152.183.205  no       
catalogue                                 active      1  catalogue-k8s                 latest/stable   38  10.152.183.147  no       
external-ca                               active      1  self-signed-certificates      latest/edge    147  10.152.183.247  no       
grafana                          9.5.3    active      1  grafana-k8s                   latest/stable  113  10.152.183.80   no       
loki                             2.9.6    active      1  loki-k8s                      latest/edge    158  10.152.183.104  no       
prometheus                       2.50.1   active      1  prometheus-k8s                latest/stable  189  10.152.183.211  no       
scrape-interval-config-metrics   n/a      active      1  prometheus-scrape-config-k8s  latest/stable   48  10.152.183.245  no       
scrape-interval-config-monitors  n/a      active      1  prometheus-scrape-config-k8s  latest/stable   48  10.152.183.155  no       
traefik                          v2.11.0  active      1  traefik-k8s                   latest/stable  191  10.4.26.66      no       

Unit                                Workload  Agent  Address       Ports  Message
alertmanager/0*                     active    idle   10.1.151.76          
ca/0*                               active    idle   10.1.151.78          
catalogue/0*                        active    idle   10.1.100.134         
external-ca/0*                      active    idle   10.1.151.79          
grafana/0*                          active    idle   10.1.35.151          
loki/0*                             active    idle   10.1.151.87          
prometheus/0*                       active    idle   10.1.35.152          
scrape-interval-config-metrics/0*   active    idle   10.1.100.135         
scrape-interval-config-monitors/0*  active    idle   10.1.100.136         
traefik/0*                          active    idle   10.1.100.137         

Offer                            Application                      Charm                         Rev  Connected  Endpoint                  Interface                Role
alertmanager                     alertmanager                     alertmanager-k8s              113  0/0        karma-dashboard           karma_dashboard          provider
grafana                          grafana                          grafana-k8s                   113  0/0        grafana-dashboard         grafana_dashboard        requirer
loki                             loki                             loki-k8s                      158  0/0        logging                   loki_push_api            provider
prometheus                       prometheus                       prometheus-k8s                189  0/0        metrics-endpoint          prometheus_scrape        requirer
                                                                                                                receive-remote-write      prometheus_remote_write  provider
scrape-interval-config-metrics   scrape-interval-config-metrics   prometheus-scrape-config-k8s  48   0/0        configurable-scrape-jobs  prometheus_scrape        requirer
scrape-interval-config-monitors  scrape-interval-config-monitors  prometheus-scrape-config-k8s  48   1/1        configurable-scrape-jobs  prometheus_scrape        requirer

Integration provider                              Requirer                     Interface              Type     Message
alertmanager:alerting                             loki:alertmanager            alertmanager_dispatch  regular  
alertmanager:alerting                             prometheus:alertmanager      alertmanager_dispatch  regular  
alertmanager:grafana-dashboard                    grafana:grafana-dashboard    grafana_dashboard      debug2: channel 0: window 1996859 sent adjust 100293
regular  
alertmanager:grafana-source                       grafana:grafana-source       grafana_datasource     regular  
alertmanager:replicas                             alertmanager:replicas        alertmanager_replica   peer     
alertmanager:self-metrics-endpoint                prometheus:metrics-endpoint  prometheus_scrape      regular  
ca:certificates                                   alertmanager:certificates    tls-certificates       regular  
ca:certificates                                   catalogue:certificates       tls-certificates       regular  
ca:certificates                                   grafana:certificates         tls-certificates       regular  
ca:certificates                                   loki:certificates            tls-certificates       regular  
ca:certificates                                   prometheus:certificates      tls-certificates       regular  
ca:send-ca-cert                                   traefik:receive-ca-cert      certificate_transfer   regular  
catalogue:catalogue                               alertmanager:catalogue       catalogue              regular  
catalogue:catalogue                               grafana:catalogue            catalogue              regular  
catalogue:catalogue                               prometheus:catalogue         catalogue              regular  
catalogue:replicas                                catalogue:replicas           catalogue_replica      peer     
external-ca:certificates                          traefik:certificates         tls-certificates       regular  
grafana:grafana                                   grafana:grafana              grafana_peers          peer     
grafana:metrics-endpoint                          prometheus:metrics-endpoint  prometheus_scrape      regular  
grafana:replicas                                  grafana:replicas             grafana_replicas       peer     
loki:grafana-dashboard                            grafana:grafana-dashboard    grafana_dashboard      regular  
loki:grafana-source                               grafana:grafana-source       grafana_datasource     regular  
loki:metrics-endpoint                             prometheus:metrics-endpoint  prometheus_scrape      regular  
loki:replicas                                     loki:replicas                loki_replica           peer     
prometheus:grafana-dashboard                      grafana:grafana-dashboard    grafana_dashboard      regular  
prometheus:grafana-source                         grafana:grafana-source       grafana_datasource     regular  
prometheus:prometheus-peers                       prometheus:prometheus-peers  prometheus_peers       peer     
scrape-interval-config-metrics:metrics-endpoint   prometheus:metrics-endpoint  prometheus_scrape      regular  
scrape-interval-config-monitors:metrics-endpoint  prometheus:metrics-endpoint  prometheus_scrape      regular  
traefik:ingress                                   alertmanager:ingress         ingress                regular  
traefik:ingress                                   catalogue:ingress            ingress                regular  
traefik:ingress-per-unit                          loki:ingress                 ingress_per_unit       regular  
traefik:ingress-per-unit                          prometheus:ingress           ingress_per_unit       regular  
traefik:metrics-endpoint                          prometheus:metrics-endpoint  prometheus_scrape      regular  
traefik:peers                                     traefik:peers                traefik_peers          peer     
traefik:traefik-route                             grafana:ingress              traefik_route          regular  
```

### Environment

Juju 3.5.1
Openstack Yoga
grafana-k8s latest/stable (but I also tried with latest/edge - same result)

### Relevant log output

```shell
Juju debug-log doesn't contain any errors, jus status updates. 
Same for kubectl logs -n cos grafana-0 for both charm and grafana containers.
```
