### ISSUE TITLE
The generated grafana source contains duplicate schemes

### ISSUE THREAD

**Issue by simskij** [canonical/grafana-k8s-operator#87]
### Bug Description

Relating a Prometheus unit to Grafana incorrectly writes a data source to disk that includes dual scheme parts.

Bug is [here](https://github.com/canonical/grafana-k8s-operator/blob/9b3de5ce2b20c01f4891fe0e86e4d89153106589/lib/charms/grafana_k8s/v0/grafana_source.py#L507-L512)

### To Reproduce

1. `juju deploy prometheus-k8s --channel=edge`
2. `juju deploy grafana-k8s --channel=edge`
3. `juju relate prometheus-k8s:grafana-source grafana-k8s`

### Environment

N/A

### Relevant log output

```shell
root@grafana-0:/etc/grafana/provisioning/datasources# cat datasources.yaml 
apiVersion: 1
datasources:
- access: proxy
  isDefault: 'false'
  name: juju_cos_1c9d8fff-d8e0-4b2e-81fc-8739256dec47_prometheus_0
  orgId: '1'
  type: prometheus
  url: http://http://prometheus-0.prometheus-endpoints.cos.svc.cluster.local:9090
- access: proxy
  isDefault: 'false'
  name: juju_cos_1c9d8fff-d8e0-4b2e-81fc-8739256dec47_loki_0
  orgId: '1'
  type: loki
  url: http://10.1.151.82:3100
deleteDatasources: []
root@grafana-0:/etc/grafana/provisioning/datasources#
```

### Additional context

```
  - endpoint: grafana-source
    related-endpoint: grafana-source
    application-data:
      grafana_source_data: '{"model": "cos", "model_uuid": "1c9d8fff-d8e0-4b2e-81fc-8739256dec47",
        "application": "prometheus", "type": "prometheus"}'
    related-units:
      prometheus/0:
        in-scope: true
        data:
          egress-subnets: 10.152.183.231/32
          grafana_source_host: http://prometheus-0.prometheus-endpoints.cos.svc.cluster.local:9090
          ingress-address: 10.152.183.231
          private-address: 10.152.183.231
```
